name: TimeStamp

on:
  workflow_dispatch:
  push:
    branches:
      - main
jobs:
  build:
    name: Build Push Image
    runs-on: ubuntu-latest
    timeout-minutes: 30
    steps:
      - uses: actions/checkout@v3
      - run: |
          echo ${{ github.sha }}-$(date +'%Y%m%d%H%M')
